export {default as HomeRoute} from './home.routes.js'
export {default as UserRoute} from './user.routes.js'
export {default as CategoryRoute} from './category.routes.js'
export {default as AuthRoute} from './auth.routes.js'
export {default as PostRoute} from './post.routes.js'
export {default as AdminRoute} from './admin.routes.js'